### ISSUE TITLE
The Twitter handle field on user profile is not long enough

### ISSUE THREAD

**Issue by nanjekyejoannah-zz** [CTPUG/pyconza2016#11]
While editing my details , my twitter handle could not fit in the text box provided only part of it could therefore pointing people to a profile that does not exist on twitter.

**Comment by nanjekyejoannah-zz** [comment]
Noticed that when filling the field putting the details without the @ solves since you automatically prepend the @.

**Comment by confluence** [comment]
Hi, Joannah

This is an issue in [Wafer](https://github.com/CTPUG/wafer), the web framework used to run the PyConZA site.

I briefly looked through the code, and it looks like the maximum permitted length for a Twitter handle is currently 15 characters (which is also the maximum allowed by Twitter) -- but your Twitter handle is exactly 15 characters. How many characters get cut off when you try to enter your full handle?

**Comment by nanjekyejoannah-zz** [comment]
like one character the very last..but that happens if I have prepended the @ I noticed.

**Comment by confluence** [comment]
Hmm, maybe this is an off-by-one error! Will you file a new issue with Wafer, or would you like me to do it?

**Comment by confluence** [comment]
Joannah, are you maybe trying to enter the handle with an @ as the first character? You should leave it out. I am able to enter a 15-character handle.

**Comment by nanjekyejoannah-zz** [comment]
My question would be...do you have a reason for not allowing users to prepend the @? If it is genuine then this ceases to be an issue but how the system works then. Because the assumption is users need not put the @ as first character when filling that field.

**Comment by confluence** [comment]
The @ is just a decoration which is automatically added when the handle is displayed on the profile page. But not all uses of the handle include the @ -- for example the URL to the account does not include it. So we store the handle without it, and the entry field assumes that you will omit it.

**Comment by nanjekyejoannah-zz** [comment]
I think I really agree with you on this..though it may be one of those usability issues.Now, just as a   suggestion that if we got a user like me who prepends the @ cant we just ignore the first character while storing data for that field but allow her fill a handle with the @ (meaning we allow to 16 characters)since it is semantically correct(users are used to this anyway). We all know whenever you are asked for a handle I begin my statement with @blablah...

**Comment by confluence** [comment]
It may be a good idea to detect if the user has entered an @ and strip it off if necessary. Maybe file this as a feature request in the Wafer repo. :)

Or we could display an @ before the text entry to make it clearer that it should be omitted.

**Comment by nanjekyejoannah-zz** [comment]
Great..Thanks :) You can close this I guess.

**Comment by hodgestar** [comment]
I believe 15 characters is the limit for Twitter handles. Stripping any leading `@` is a good idea though.

**Comment by nanjekyejoannah-zz** [comment]
And I think this can also be achieved on the [pyconza2016](https://github.com/CTPUG/pyconza2016)  end.
